const NOME_MIN_LENGTH = 3;
const NOME_MAX_LENGTH = 100;

const EMAIL_MIN_LENGTH = 5;
const EMAIL_MAX_LENGTH = 100;

const SENHA_MIN_LENGTH = 6;
const SENHA_MAX_LENGTH = 16;

export {
  EMAIL_MAX_LENGTH,
  EMAIL_MIN_LENGTH,
  NOME_MAX_LENGTH,
  NOME_MIN_LENGTH,
  SENHA_MAX_LENGTH,
  SENHA_MIN_LENGTH,
};
